# Generated by Django 6.1 on 2026-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='podcast_images/')),
                ('audio_file', models.FileField(upload_to='podcast_audio/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
