# Generated by Django 6.1 on 2026-09-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='podcast_audio/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='podcast_images/'),
        ),
    ]
